"""
backend/api/routes_upload.py

Document Upload API controller.

Endpoints:
    POST   /api/upload            upload and locally store a file
    GET    /api/upload            list uploaded files
    GET    /api/upload/{file_id}  get file metadata
    DELETE /api/upload/{file_id}  delete a file

Architecture notes (read before changing anything here):

  - The requested contract files "backend/database/db_models.py",
    "backend/database/crud.py", "backend/knowledge_base/ingestion.py" and
    "backend/config.py" do not exist in this repository. The real,
    implemented equivalents are "database/db_models.py" and
    "database/crud.py" (top-level, not under backend/) -- both inspected
    before writing this file. "knowledge_base/ingestion.py" and
    "backend/config.py" are not implemented at all yet.

  - database/db_models.py defines Conversation and Message only -- there is
    no UploadedFile/Document table. Since modifying the database
    architecture is explicitly out of scope, and there is no existing
    model to "reuse" for uploads, file metadata is stored as a small JSON
    sidecar next to each file on disk (<file_id>.meta.json) rather than in
    SQL. This avoids inventing a second, conflicting persistence layer
    while staying fully local/offline. If database/db_models.py later
    grows an UploadedFile table, this file's storage functions are the
    only thing that would need to change.

  - knowledge_base/ingestion.py does not exist, so upload does NOT trigger
    ingestion (per this task's own instruction: only integrate ingestion
    if the existing architecture explicitly requires it during upload --
    it doesn't, since that module isn't implemented). A file becomes
    searchable once ingestion.py exists and is explicitly wired to read
    from data/uploads/.

  - backend/config.py does not exist, so configuration is read directly
    from environment variables (MAX_UPLOAD_SIZE_MB, UPLOAD_ROOT), matching
    the pattern already used in database/init_db.py and
    backend/model_router/router.py.

  - Only three upload directories exist in the project's architecture:
    data/uploads/scanned_pdfs/, data/uploads/drawings/, data/uploads/images/.
    Ten file types must be supported across only these three folders:
        .pdf                                  -> scanned_pdfs/  (category "pdf")
        .png .jpg .jpeg .webp .tiff .tif .bmp  -> images/       (category "image")
        .docx .txt .csv .xls .xlsx             -> drawings/     (category "document")
    The public "category" value is a semantic label, not the literal
    folder name -- API responses never reveal internal directory layout
    or any filesystem path.

Requires `python-multipart` at runtime (FastAPI's UploadFile/File(...)
dependency needs it); not yet listed in requirements.txt.

No cloud APIs, no external network calls: every operation here is local
filesystem I/O under data/uploads/.
"""

from __future__ import annotations

import json
import logging
import os
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from fastapi import APIRouter, File, HTTPException, UploadFile, status

from backend.api.schemas import BaseSchema

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/upload", tags=["Upload"])


# ---------------------------------------------------------------------------
# Configuration (env vars -- backend/config.py does not exist yet)
# ---------------------------------------------------------------------------

UPLOAD_ROOT = Path(os.getenv("UPLOAD_ROOT", "data/uploads"))
MAX_UPLOAD_SIZE_BYTES = int(os.getenv("MAX_UPLOAD_SIZE_MB", "25")) * 1024 * 1024
_READ_CHUNK_SIZE = 1024 * 1024  # stream in 1 MB chunks so a huge upload is rejected before full buffering

_EXTENSION_TO_FOLDER: Dict[str, str] = {
    ".pdf": "scanned_pdfs",
    ".png": "images",
    ".jpg": "images",
    ".jpeg": "images",
    ".webp": "images",
    ".tiff": "images",
    ".tif": "images",
    ".bmp": "images",
    ".docx": "drawings",
    ".txt": "drawings",
    ".csv": "drawings",
    ".xls": "drawings",
    ".xlsx": "drawings",
}

_FOLDER_TO_CATEGORY: Dict[str, str] = {
    "scanned_pdfs": "pdf",
    "images": "image",
    "drawings": "document",
}

_FILE_ID_PATTERN = re.compile(r"^[0-9a-f]{32}$")  # matches uuid4().hex, generated by this module only
_SAFE_FILENAME_CHARS = re.compile(r"[^A-Za-z0-9._-]+")
_MAX_DISPLAY_FILENAME_LENGTH = 150


# ---------------------------------------------------------------------------
# Response schemas (new to this endpoint; reuses BaseSchema's config from
# backend/api/schemas.py rather than duplicating it, without modifying that file)
# ---------------------------------------------------------------------------


class UploadedFileMetadata(BaseSchema):
    file_id: str
    filename: str
    content_type: str
    category: str  # "pdf" | "image" | "document" -- never an internal folder name
    size_bytes: int
    uploaded_at: datetime


class UploadedFileList(BaseSchema):
    files: List[UploadedFileMetadata]
    count: int


class DeleteUploadResponse(BaseSchema):
    file_id: str
    deleted: bool


# ---------------------------------------------------------------------------
# Local storage helpers
# ---------------------------------------------------------------------------


def _sanitize_filename(filename: str) -> str:
    """
    Reduce a client-supplied filename to a safe display name: strip any
    directory components (prevents path traversal via filename), allow
    only a conservative character set, and cap the length.
    """
    base = os.path.basename(filename or "")
    base = _SAFE_FILENAME_CHARS.sub("_", base).strip("._") or "upload"
    return base[:_MAX_DISPLAY_FILENAME_LENGTH]


def _resolve_folder_and_category(extension: str) -> Optional[tuple[str, str]]:
    folder = _EXTENSION_TO_FOLDER.get(extension.lower())
    if folder is None:
        return None
    return folder, _FOLDER_TO_CATEGORY[folder]


def _meta_path(folder: str, file_id: str) -> Path:
    return UPLOAD_ROOT / folder / f"{file_id}.meta.json"


def _file_path(folder: str, file_id: str, extension: str) -> Path:
    return UPLOAD_ROOT / folder / f"{file_id}{extension}"


def _find_meta_path(file_id: str) -> Optional[Path]:
    """Locate a file's metadata sidecar without assuming which of the three folders it's in."""
    for folder in _FOLDER_TO_CATEGORY:
        candidate = _meta_path(folder, file_id)
        if candidate.exists():
            return candidate
    return None


def _read_metadata(meta_path: Path) -> dict:
    with meta_path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _write_metadata(meta_path: Path, data: dict) -> None:
    with meta_path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh)


def _to_public_metadata(data: dict) -> UploadedFileMetadata:
    """Project the on-disk record down to exactly the public fields -- e.g. drops the internal 'extension' key."""
    return UploadedFileMetadata(
        file_id=data["file_id"],
        filename=data["filename"],
        content_type=data["content_type"],
        category=data["category"],
        size_bytes=data["size_bytes"],
        uploaded_at=data["uploaded_at"],
    )


def _validate_file_id(file_id: str) -> None:
    """
    Reject anything that isn't exactly the shape this module generates
    (a uuid4 hex string) before it's ever used to build a filesystem path --
    the core defense against path traversal via the file_id URL parameter.
    """
    if not _FILE_ID_PATTERN.match(file_id):
        raise HTTPException(status.HTTP_404_NOT_FOUND, "File not found.")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post("", response_model=UploadedFileMetadata, status_code=status.HTTP_201_CREATED)
async def upload_file(file: UploadFile = File(...)) -> UploadedFileMetadata:
    """
    Upload and locally store a file under data/uploads/. Rejects
    unsupported file types and files over MAX_UPLOAD_SIZE_BYTES. Does not
    trigger knowledge-base ingestion (see module docstring).
    """
    original_name = file.filename or "upload"
    extension = Path(original_name).suffix.lower()

    resolved = _resolve_folder_and_category(extension)
    if resolved is None:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported file type '{extension or 'unknown'}'.",
        )
    folder, category = resolved

    chunks: List[bytes] = []
    total_size = 0
    try:
        while True:
            chunk = await file.read(_READ_CHUNK_SIZE)
            if not chunk:
                break
            total_size += len(chunk)
            if total_size > MAX_UPLOAD_SIZE_BYTES:
                raise HTTPException(
                    status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                    detail=f"File exceeds the maximum allowed size of {MAX_UPLOAD_SIZE_BYTES // (1024 * 1024)} MB.",
                )
            chunks.append(chunk)
    finally:
        await file.close()

    if total_size == 0:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Uploaded file is empty.")

    file_id = uuid.uuid4().hex
    safe_display_name = _sanitize_filename(original_name)
    target_dir = UPLOAD_ROOT / folder

    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        with _file_path(folder, file_id, extension).open("wb") as fh:
            for chunk in chunks:
                fh.write(chunk)

        record = {
            "file_id": file_id,
            "filename": safe_display_name,
            "content_type": file.content_type or "application/octet-stream",
            "category": category,
            "size_bytes": total_size,
            "uploaded_at": datetime.utcnow().isoformat(),
            "extension": extension,  # internal only, used to locate the file for deletion; not in the public schema
        }
        _write_metadata(_meta_path(folder, file_id), record)
    except OSError:
        logger.exception("Failed to save uploaded file '%s'.", safe_display_name)
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "Failed to store the uploaded file.")

    logger.info("Stored upload '%s' (file_id=%s, category=%s, %d bytes).", safe_display_name, file_id, category, total_size)
    return _to_public_metadata(record)


@router.get("", response_model=UploadedFileList)
async def list_uploaded_files() -> UploadedFileList:
    """List all uploaded files' metadata, most recent first."""
    files: List[UploadedFileMetadata] = []
    for folder in _FOLDER_TO_CATEGORY:
        folder_path = UPLOAD_ROOT / folder
        if not folder_path.exists():
            continue
        for meta_file in folder_path.glob("*.meta.json"):
            try:
                files.append(_to_public_metadata(_read_metadata(meta_file)))
            except (OSError, json.JSONDecodeError, KeyError):
                logger.warning("Skipping unreadable metadata file '%s'.", meta_file, exc_info=True)

    files.sort(key=lambda f: f.uploaded_at, reverse=True)
    return UploadedFileList(files=files, count=len(files))


@router.get("/{file_id}", response_model=UploadedFileMetadata)
async def get_uploaded_file_metadata(file_id: str) -> UploadedFileMetadata:
    """Get metadata for a single uploaded file."""
    _validate_file_id(file_id)

    meta_path = _find_meta_path(file_id)
    if meta_path is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "File not found.")

    try:
        record = _read_metadata(meta_path)
    except (OSError, json.JSONDecodeError):
        logger.exception("Failed to read metadata for file_id='%s'.", file_id)
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "Failed to read file metadata.")

    return _to_public_metadata(record)


@router.delete("/{file_id}", response_model=DeleteUploadResponse)
async def delete_uploaded_file(file_id: str) -> DeleteUploadResponse:
    """Delete an uploaded file and its metadata."""
    _validate_file_id(file_id)

    meta_path = _find_meta_path(file_id)
    if meta_path is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "File not found.")

    folder = meta_path.parent.name
    try:
        record = _read_metadata(meta_path)
    except (OSError, json.JSONDecodeError):
        record = {}

    extension = record.get("extension", "")

    try:
        meta_path.unlink(missing_ok=True)
        if extension:
            _file_path(folder, file_id, extension).unlink(missing_ok=True)
    except OSError:
        logger.exception("Failed to delete file_id='%s'.", file_id)
        raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, "Failed to delete the file.")

    logger.info("Deleted upload file_id='%s'.", file_id)
    return DeleteUploadResponse(file_id=file_id, deleted=True)