"""
backend/agent/executer.py

Execution layer for the Sovereign AI Workbench agent.

Responsibilities:
- Validate a planner-generated plan.
- Execute plan steps sequentially.
- Dispatch each step to a registered backend tool.
- Pass previous step outputs to later steps using $step_N references.
- Capture step-level success/failure.
- Support both synchronous and asynchronous tools.

The executor does NOT:
- generate plans,
- call the LLM directly,
- select models,
- implement individual tools,
- access the database directly.
"""

from __future__ import annotations

import inspect
import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Mapping, Optional


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class ExecutorError(Exception):
    """Base exception for executor errors."""


class InvalidPlanError(ExecutorError):
    """Raised when the supplied plan is invalid."""


class ToolNotFoundError(ExecutorError):
    """Raised when a requested tool is not registered."""


class ToolExecutionError(ExecutorError):
    """Raised when execution of a tool fails."""


# ---------------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------------


@dataclass
class StepResult:
    """Result produced by one executed plan step."""

    step_id: str
    tool: str
    success: bool
    output: Any = None
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "step_id": self.step_id,
            "tool": self.tool,
            "success": self.success,
            "output": self.output,
            "error": self.error,
        }


@dataclass
class ExecutionResult:
    """Complete result of plan execution."""

    success: bool
    results: List[StepResult] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "results": [
                result.to_dict()
                for result in self.results
            ],
        }

    @property
    def outputs(self) -> Dict[str, Any]:
        """
        Return successful step outputs indexed by step ID.
        """

        return {
            result.step_id: result.output
            for result in self.results
            if result.success
        }


# ---------------------------------------------------------------------------
# Tool type
# ---------------------------------------------------------------------------


ToolCallable = Callable[..., Any]


# ---------------------------------------------------------------------------
# Executor
# ---------------------------------------------------------------------------


class Executor:
    """
    Executes structured plans generated by Planner.

    Expected plan format:

        {
            "goal": "Calculate 25 + 25",
            "task_type": "code",
            "steps": [
                {
                    "id": "step_1",
                    "tool": "code_exec",
                    "args": {
                        "code": "print(25 + 25)"
                    },
                    "continue_on_error": false
                }
            ]
        }

    Tools are injected into the executor:

        Executor(
            tools={
                "code_exec": code_exec_function,
                "file_rw": file_rw_function,
            }
        )

    This keeps the executor independent from concrete tool
    implementations.
    """

    def __init__(
        self,
        tools: Optional[Mapping[str, ToolCallable]] = None,
    ) -> None:
        self._tools: Dict[str, ToolCallable] = dict(tools or {})

    # -----------------------------------------------------------------------
    # Tool registration
    # -----------------------------------------------------------------------

    def register_tool(
        self,
        name: str,
        tool: ToolCallable,
    ) -> None:
        """
        Register a tool.

        The actual implementation of the tool remains inside backend/tools/.
        """

        if not isinstance(name, str) or not name.strip():
            raise ValueError(
                "Tool name must be a non-empty string."
            )

        if not callable(tool):
            raise TypeError(
                f"Tool '{name}' must be callable."
            )

        self._tools[name.strip()] = tool

    def unregister_tool(self, name: str) -> None:
        """Remove a registered tool."""

        self._tools.pop(name, None)

    def available_tools(self) -> List[str]:
        """Return names of all currently registered tools."""

        return sorted(self._tools.keys())

    # -----------------------------------------------------------------------
    # Plan validation
    # -----------------------------------------------------------------------

    @staticmethod
    def _validate_plan(
        plan: Mapping[str, Any],
    ) -> None:
        """
        Validate the planner -> executor contract.
        """

        if not isinstance(plan, Mapping):
            raise InvalidPlanError(
                "Plan must be a dictionary-like object."
            )

        steps = plan.get("steps")

        if not isinstance(steps, list):
            raise InvalidPlanError(
                "Plan must contain a 'steps' list."
            )

        seen_ids = set()

        for index, step in enumerate(steps, start=1):

            if not isinstance(step, Mapping):
                raise InvalidPlanError(
                    f"Step {index} must be a dictionary-like object."
                )

            step_id = step.get("id")

            if not isinstance(step_id, str) or not step_id.strip():
                raise InvalidPlanError(
                    f"Step {index} must contain a non-empty 'id'."
                )

            if step_id in seen_ids:
                raise InvalidPlanError(
                    f"Duplicate step id: '{step_id}'."
                )

            seen_ids.add(step_id)

            tool = step.get("tool")

            if not isinstance(tool, str) or not tool.strip():
                raise InvalidPlanError(
                    f"Step '{step_id}' must contain a non-empty 'tool'."
                )

            args = step.get("args", {})

            if not isinstance(args, Mapping):
                raise InvalidPlanError(
                    f"Step '{step_id}' args must be a dictionary."
                )

            continue_on_error = step.get(
                "continue_on_error",
                False,
            )

            if not isinstance(continue_on_error, bool):
                raise InvalidPlanError(
                    f"Step '{step_id}' continue_on_error "
                    "must be boolean."
                )

    # -----------------------------------------------------------------------
    # Argument reference resolution
    # -----------------------------------------------------------------------

    @staticmethod
    def _resolve_references(
        value: Any,
        previous_outputs: Mapping[str, Any],
    ) -> Any:
        """
        Resolve references such as:

            "$step_1"

        into the output of step_1.

        Supports nested dictionaries and lists.
        """

        if isinstance(value, str):

            if value.startswith("$"):
                reference = value[1:]

                if reference in previous_outputs:
                    return previous_outputs[reference]

            return value

        if isinstance(value, list):
            return [
                Executor._resolve_references(
                    item,
                    previous_outputs,
                )
                for item in value
            ]

        if isinstance(value, dict):
            return {
                key: Executor._resolve_references(
                    item,
                    previous_outputs,
                )
                for key, item in value.items()
            }

        return value

    # -----------------------------------------------------------------------
    # Tool invocation
    # -----------------------------------------------------------------------

    async def _invoke_tool(
        self,
        tool_name: str,
        args: Mapping[str, Any],
    ) -> Any:
        """
        Invoke a registered synchronous or asynchronous tool.
        """

        tool = self._tools.get(tool_name)

        if tool is None:
            raise ToolNotFoundError(
                f"Tool '{tool_name}' is not registered."
            )

        try:
            result = tool(**dict(args))

            if inspect.isawaitable(result):
                result = await result

            return result

        except ExecutorError:
            raise

        except Exception as exc:
            raise ToolExecutionError(
                f"Tool '{tool_name}' failed: {exc}"
            ) from exc

    # -----------------------------------------------------------------------
    # Main execution
    # -----------------------------------------------------------------------

    async def execute(
        self,
        plan: Mapping[str, Any],
    ) -> ExecutionResult:
        """
        Execute the supplied planner-generated plan sequentially.

        Execution stops at the first failed step unless that step contains:

            "continue_on_error": true
        """

        self._validate_plan(plan)

        steps = plan["steps"]

        results: List[StepResult] = []

        previous_outputs: Dict[str, Any] = {}

        for step in steps:

            step_id = step["id"]
            tool_name = step["tool"]

            raw_args = step.get("args", {})

            continue_on_error = step.get(
                "continue_on_error",
                False,
            )

            resolved_args = self._resolve_references(
                raw_args,
                previous_outputs,
            )

            logger.info(
                "Executing agent step '%s' using tool '%s'.",
                step_id,
                tool_name,
            )

            try:

                output = await self._invoke_tool(
                    tool_name,
                    resolved_args,
                )

                result = StepResult(
                    step_id=step_id,
                    tool=tool_name,
                    success=True,
                    output=output,
                )

                results.append(result)

                previous_outputs[step_id] = output

            except Exception as exc:

                logger.exception(
                    "Agent step '%s' failed.",
                    step_id,
                )

                result = StepResult(
                    step_id=step_id,
                    tool=tool_name,
                    success=False,
                    error=str(exc),
                )

                results.append(result)

                if not continue_on_error:
                    return ExecutionResult(
                        success=False,
                        results=results,
                    )

        return ExecutionResult(
            success=all(
                result.success
                for result in results
            ),
            results=results,
        )


# ---------------------------------------------------------------------------
# Shared executor
# ---------------------------------------------------------------------------


_default_executor: Optional[Executor] = None


def get_executor() -> Executor:
    """
    Return the shared executor instance.

    Tools are intentionally not automatically registered here yet.

    Concrete tools will be connected after their interfaces are finalized.
    """

    global _default_executor

    if _default_executor is None:
        _default_executor = Executor()

    return _default_executor


__all__ = [
    "Executor",
    "ExecutionResult",
    "StepResult",
    "ExecutorError",
    "InvalidPlanError",
    "ToolNotFoundError",
    "ToolExecutionError",
    "get_executor",
]